name: "Airgap tests"
run-name: >-
  ${{ github.event_name == 'workflow_dispatch' &&
      format('[{1}] Airgap tests on Rancher-`{0}`', inputs.rancher_version, github.run_number) }}
on:
  workflow_dispatch:
    inputs:
      rancher_version:
        description: Rancher Manager channel/version to use for airgap checks
        default: prime/2.14.2
        type: string

jobs:
  airgap-precheck:
    env:
      RANCHER_VERSION: ${{ inputs.rancher_version }}
      PRIME_REGISTRY: ${{ secrets.PRIME_REGISTRY }}
      STG_PRIME_REGISTRY: ${{ secrets.STG_PRIME_REGISTRY }}
      PRIME_ARTIFACTS_URL: ${{ secrets.PRIME_ARTIFACTS_URL }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          cache: true
          go-version-file: tests/go.mod
          cache-dependency-path: tests/go.mod
      - name: Airgap precheck tests
        run: cd tests && make e2e-airgap-precheck
