name: Lint

on:
  pull_request:

jobs:
  golang-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: tests/go.sum
          go-version-file: tests/go.mod

      - name: Analysis
        uses: golangci/golangci-lint-action@v4
        with:
          args: -v
          working-directory: tests

  cypress-lint:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: current
      WORKING_DIR: tests/cypress/latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install npm
        run: |
          cd ${{ env.WORKING_DIR }}
          npm install --save-dev
          npm ls --depth=0

      - name: Analysis
        run: |
          cd ${{ env.WORKING_DIR }}
          npm run lint