#!/bin/bash

# This script deploys a local helm repo to host the turtles dev chart
# because it is not exported anywhere else.

set -eo pipefail

# Set the caller as the user that will run the service
CALLER=${SUDO_USER:-$(whoami)}

# Create a systemctl file for chartmuseum
cat > /etc/systemd/system/chartmuseum.service << EOF
[Unit]
Description=Chartmuseum server

[Service]
Type=simple
User=${CALLER}
Group=users

Environment=DEBUG=1
Environment=STORAGE=local
Environment=STORAGE_LOCAL_ROOTDIR=/home/${CALLER}/charts

WorkingDirectory=/tmp
ExecStart=/usr/local/bin/chartmuseum --port=8080

[Install]
WantedBy=multi-user.target
EOF

# Download and install chartmuseum
# Due to GH API rate limiting, we need to specify the chartmuseum version
CHARTMUSEUM_VERSION="v0.16.5"
CHARTMUSEUM_INSTALLER_SHA256="f1116c09104abb4610b5d00be0ef80e625ec44838fb10e9fb042d16970f79356" # v0.16.5
export DESIRED_VERSION=${CHARTMUSEUM_VERSION}
curl https://raw.githubusercontent.com/helm/chartmuseum/refs/tags/${CHARTMUSEUM_VERSION}/scripts/get-chartmuseum -o get-chartmuseum.sh
echo "${CHARTMUSEUM_INSTALLER_SHA256}  get-chartmuseum.sh" | sha256sum -c -
chmod +x get-chartmuseum.sh
./get-chartmuseum.sh

# Start chartmuseum
systemctl start chartmuseum

# Download and install helm-push plugin and do not fail if exists
helm plugin install https://github.com/chartmuseum/helm-push.git --version 0.10.4 || true

# Create a local helm repo
helm repo add chartmuseum http://localhost:8080

# Push helm chart to local repo even when exists already
helm cm-push --force ./assets/rancher-turtles-*.tgz chartmuseum || true
helm cm-push --force ./assets/providers/rancher-turtles-providers-*.tgz chartmuseum || true
